/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimall;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author 1styrGroupB
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
    }
    String productsubtotal;
    String customermoney;
    String customerbalance;
    
    
    
    
    
    
     public receipt(String subtotal,String money, String balance, TableModel tableModel) throws PrinterException {
       initComponents();
       
       this.productsubtotal = subtotal;
       this.customermoney = money;
       this.customerbalance = balance;
       
       txtreceipt.setText(txtreceipt.getText()+ "-----------------------------------------------------------------\n");
       txtreceipt.setText(txtreceipt.getText()+ "---------------------------MiniTechShop--------------------------\n");
       txtreceipt.setText(txtreceipt.getText()+ "\n");
       txtreceipt.setText(txtreceipt.getText()+ "Product" + "\t" + "Price" + "\t" + "Total");
       
       for (int i = 0; i< tableModel.getRowCount(); i++)
       {
           String product = (String) tableModel.getValueAt(i, 1);
           String price = (String) tableModel.getValueAt(i, 2);
           int total = (int) tableModel.getValueAt(i, 4);
           
           txtreceipt.setText(txtreceipt.getText()+ product +    "\t" + price +    "\t" + total);
       }
       txtreceipt.setText(txtreceipt.getText()+ "\n");
       txtreceipt.setText(txtreceipt.getText()+ "\n");
       
       txtreceipt.setText(txtreceipt.getText()+ "              "    + "SubTotal: " +  subtotal +      "\n");
       txtreceipt.setText(txtreceipt.getText()+ "              "    + "Money: " +  money +      "\n");
       txtreceipt.setText(txtreceipt.getText()+ "              "    + "Balance: " +  balance+      "\n");
       
       txtreceipt.setText(txtreceipt.getText()+ "----------------------------------------\n");
       txtreceipt.setText(txtreceipt.getText()+ "----------------------------------------\n");
       txtreceipt.setText(txtreceipt.getText()+ "This software is Verisign as a Secure and Trusted site\n");
       txtreceipt.setText(txtreceipt.getText()+ "Thank You!");
       
       txtreceipt.print();
       
     }
    
    
    
    
    
    
    

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtreceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(210, 307));

        txtreceipt.setColumns(20);
        txtreceipt.setRows(5);
        jScrollPane1.setViewportView(txtreceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtreceipt;
    // End of variables declaration//GEN-END:variables
}
