/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryCashiering;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.ResultSetMetaData;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 1styrGroupB
 */
public class admin extends javax.swing.JFrame {
       Connection con;
       PreparedStatement prest;
       ResultSet result;
    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        table_update();
    
    }
      private void table_update() {
    try {
      try {
        Class.forName("com.mysql.jdbc.Driver");
        this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
        this.prest = (PreparedStatement)this.con.prepareStatement("select * from users");
        ResultSet result = (ResultSet)this.prest.executeQuery();
        ResultSetMetaData set = (ResultSetMetaData)result.getMetaData();
        int mini = set.getColumnCount();
        DefaultTableModel dtm = (DefaultTableModel)this.jTable1.getModel();
        dtm.setRowCount(0);
        while (result.next()) {
          Vector<String> vc = new Vector();
          for (int i = 1; i <= mini; i++) {
            vc.add(result.getString("userid"));
            vc.add(result.getString("first_name"));
            vc.add(result.getString("last_name"));
            vc.add(result.getString("email"));
            vc.add(result.getString("password"));
            vc.add(result.getString("role"));
            vc.add(result.getString("status"));
          } 
          dtm.addRow(vc);
        } 
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(admin.class.getName()).log(Level.SEVERE, (String)null, ex);
      } 
    } catch (SQLException ex) {
      Logger.getLogger(admin.class.getName()).log(Level.SEVERE, (String)null, ex);
    } 
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtuserid = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtrole = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        disable = new javax.swing.JButton();
        changepassword = new javax.swing.JButton();
        changerole = new javax.swing.JButton();
        manage = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("User Id:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Email:");

        jLabel5.setText("Password:");

        jLabel6.setText("Role:");

        jLabel7.setText("Status:");

        txtuserid.setBackground(new java.awt.Color(204, 204, 204));
        txtuserid.setForeground(new java.awt.Color(153, 153, 153));
        txtuserid.setText("UserId.....");
        txtuserid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtuserid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuseridMouseClicked(evt);
            }
        });

        txtfirstname.setBackground(new java.awt.Color(204, 204, 204));
        txtfirstname.setForeground(new java.awt.Color(153, 153, 153));
        txtfirstname.setText("FirstName.....");
        txtfirstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtfirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfirstnameMouseClicked(evt);
            }
        });

        txtlastname.setBackground(new java.awt.Color(204, 204, 204));
        txtlastname.setForeground(new java.awt.Color(153, 153, 153));
        txtlastname.setText("LastName.....");
        txtlastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtlastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlastnameMouseClicked(evt);
            }
        });

        txtemail.setBackground(new java.awt.Color(204, 204, 204));
        txtemail.setForeground(new java.awt.Color(153, 153, 153));
        txtemail.setText("Email......");
        txtemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemailMouseClicked(evt);
            }
        });

        txtpassword.setBackground(new java.awt.Color(204, 204, 204));
        txtpassword.setForeground(new java.awt.Color(153, 153, 153));
        txtpassword.setText("ppppppppp");
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });

        txtrole.setBackground(new java.awt.Color(204, 204, 204));
        txtrole.setForeground(new java.awt.Color(153, 153, 153));
        txtrole.setText("Role.....");
        txtrole.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtrole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtroleMouseClicked(evt);
            }
        });

        txtstatus.setBackground(new java.awt.Color(204, 204, 204));
        txtstatus.setForeground(new java.awt.Color(153, 153, 153));
        txtstatus.setText("Status.....");
        txtstatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 255)));
        txtstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtstatusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtuserid)
                                .addComponent(txtfirstname)
                                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtrole)
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtrole, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "First Name", "Last Name", "Email", "Password", "Role", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add.setBackground(new java.awt.Color(153, 153, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setText("Add User Account");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(153, 153, 255));
        remove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remove.setText("Remove Account");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        disable.setBackground(new java.awt.Color(153, 153, 255));
        disable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disable.setText("Disable Account");
        disable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableActionPerformed(evt);
            }
        });

        changepassword.setBackground(new java.awt.Color(153, 153, 255));
        changepassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        changepassword.setText("Change Password");
        changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordActionPerformed(evt);
            }
        });

        changerole.setBackground(new java.awt.Color(153, 153, 255));
        changerole.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        changerole.setText("Change Role");
        changerole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeroleActionPerformed(evt);
            }
        });

        manage.setBackground(new java.awt.Color(255, 51, 102));
        manage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        manage.setText("Manage Users");
        manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(remove)
                        .addGap(56, 56, 56)
                        .addComponent(disable, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(changepassword)
                        .addGap(64, 64, 64)
                        .addComponent(changerole, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(483, 483, 483))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changerole, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryCashiering/sweetshop2.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Hole Bunch Sweet Shop Inventory System");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryCashiering/a.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryCashiering/exit-removebg-preview.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryCashiering/acon-removebg-preview.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryCashiering/maximize.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InventoryCashiering/minimize.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Admin Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(412, 412, 412))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordActionPerformed
    String userid = this.txtuserid.getText();
    String firstname = this.txtfirstname.getText();
    String lastname = this.txtlastname.getText();
    String email = this.txtemail.getText();
    String password = this.txtpassword.getText();
    String role = this.txtrole.getText();
    String status = this.txtstatus.getText();
    try {
      Class.forName("com.mysql.jdbc.Driver");
      this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
      Statement state = (Statement)this.con.createStatement();
      int x = 0;
      if (x == 0) {
        state.executeUpdate(" UPDATE users SET userid='" + userid + "' ,first_name ='" + firstname + "' ,last_name='" + lastname + "' ,email='" + email + "' ,password ='" + password + "' ,role ='" + role + "' , status ='" + status + "' WHERE userid = '" + userid + "'");
        JOptionPane.showMessageDialog(null, "Password has changed");
      } else {
        JOptionPane.showMessageDialog(null, "ERROR!");
      } 
    } catch (Exception e) {
      e.printStackTrace();
    } 
    }//GEN-LAST:event_changepasswordActionPerformed

    private void disableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableActionPerformed
    String userid = this.txtuserid.getText();
    String firstname = this.txtfirstname.getText();
    String lastname = this.txtlastname.getText();
    String email = this.txtemail.getText();
    String password = this.txtpassword.getText();
    String role = this.txtrole.getText();
    String status = this.txtstatus.getText();
    try {
      Class.forName("com.mysql.jdbc.Driver");
      this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
      Statement state = (Statement)this.con.createStatement();
      int x = 0;
      if (x == 0) {
        state.executeUpdate(" UPDATE users SET userid='" + userid + "' ,first_name ='" + firstname + "' ,last_name='" + lastname + "' ,email='" + email + "' ,password ='" + password + "' ,role ='" + role + "' , status ='" + status + "' WHERE userid = '" + userid + "'");
        JOptionPane.showMessageDialog(null, "Data Updated");
      } else {
        JOptionPane.showMessageDialog(null, "ERROR!");
      } 
    } catch (Exception e) {
      e.printStackTrace();
    } 
    }//GEN-LAST:event_disableActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    DefaultTableModel dtm1 = (DefaultTableModel)this.jTable1.getModel();
    try {
      int selectIndex = this.jTable1.getSelectedRow();
      String UserId = this.txtuserid.getText();
      String FirstName = this.txtfirstname.getText();
      String LastName = this.txtlastname.getText();
      String Email = this.txtemail.getText();
      String Password = this.txtpassword.getText();
      String Role = this.txtrole.getText();
      String Status = this.txtstatus.getText();
      this.txtuserid.setText(dtm1.getValueAt(selectIndex, 0).toString());
      this.txtfirstname.setText(dtm1.getValueAt(selectIndex, 1).toString());
      this.txtlastname.setText(dtm1.getValueAt(selectIndex, 2).toString());
      this.txtemail.setText(dtm1.getValueAt(selectIndex, 3).toString());
      this.txtpassword.setText(dtm1.getValueAt(selectIndex, 4).toString());
      this.txtrole.setText(dtm1.getValueAt(selectIndex, 5).toString());
      this.txtstatus.setText(dtm1.getValueAt(selectIndex, 6).toString());
    } catch (ArrayIndexOutOfBoundsException arrayIndexOutOfBoundsException) {}
    }//GEN-LAST:event_jTable1MouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    String firstname = this.txtfirstname.getText();
    String lastname = this.txtlastname.getText();
    String email = this.txtemail.getText();
    String password = this.txtpassword.getText();
    String role = this.txtrole.getText();
    String status = this.txtstatus.getText();
    try {
      Class.forName("com.mysql.jdbc.Driver");
      this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
      this.prest = (PreparedStatement)this.con.prepareStatement("insert into users (first_name,last_name,email,password,role,status)values(?,?,?,?,?,?)");
      this.prest.setString(1, firstname);
      this.prest.setString(2, lastname);
      this.prest.setString(3, email);
      this.prest.setString(4, password);
      this.prest.setString(5, role);
      this.prest.setString(6, status);
      this.prest.executeUpdate();
      JOptionPane.showMessageDialog(null, "Account Added Successfully");
      this.txtfirstname.setText("");
      this.txtlastname.setText("");
      this.txtemail.setText("");
      this.txtpassword.setText("");
      this.txtrole.setText("");
      this.txtstatus.setText("");
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(admin.class.getName()).log(Level.SEVERE, (String)null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(admin.class.getName()).log(Level.SEVERE, (String)null, ex);
    } 
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
    DefaultTableModel dtm1 = (DefaultTableModel)this.jTable1.getModel();
    int selectIndex = this.jTable1.getSelectedRow();
    int id = Integer.parseInt(dtm1.getValueAt(selectIndex, 0).toString());
    int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Remove this User Account", "Warning", 0);
    if (dialogResult == 0)
      try {
        Class.forName("com.mysql.jdbc.Driver");
        this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
        this.prest = (PreparedStatement)this.con.prepareStatement("delete from users where userid=?");
        this.prest.setInt(1, id);
        this.prest.executeUpdate();
        JOptionPane.showMessageDialog(null, "Account Successfully Deleted");
        table_update();
        this.txtfirstname.setText("");
        this.txtlastname.setText("");
        this.txtemail.setText("");
        this.txtpassword.setText("");
        this.txtrole.setText("");
        this.txtstatus.setText("");
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(admin.class.getName()).log(Level.SEVERE, (String)null, ex);
      } catch (SQLException ex) {
        Logger.getLogger(admin.class.getName()).log(Level.SEVERE, (String)null, ex);
      }  
    }//GEN-LAST:event_removeActionPerformed

    private void manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageActionPerformed
      try {
      Class.forName("com.mysql.jdbc.Driver");
      this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
      this.prest = (PreparedStatement)this.con.prepareStatement("select * from users");
      ResultSet result = (ResultSet)this.prest.executeQuery();
      ResultSetMetaData set = (ResultSetMetaData)result.getMetaData();
      int holebunchsweetshop = set.getColumnCount();
      DefaultTableModel model = (DefaultTableModel)this.jTable1.getModel();
      model.setRowCount(0);
      while (result.next()) {
        model.addRow((Object[])new String[] { result.getString(1), result.getString(2), result.getString(3), result.getString(4), result.getString(5), result.getString(6), result.getString(7) });
      } 
    } catch (ClassNotFoundException|SQLException ex) {
      System.out.println("Error : " + ex.getMessage());
    } 
    }//GEN-LAST:event_manageActionPerformed

    private void changeroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeroleActionPerformed
    String userid = this.txtuserid.getText();
    String firstname = this.txtfirstname.getText();
    String lastname = this.txtlastname.getText();
    String email = this.txtemail.getText();
    String password = this.txtpassword.getText();
    String role = this.txtrole.getText();
    String status = this.txtstatus.getText();
    try {
      Class.forName("com.mysql.jdbc.Driver");
      this.con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/holebunchsweetshop", "root", "");
      Statement state = (Statement)this.con.createStatement();
      int x = 0;
      if (x == 0) {
        state.executeUpdate(" UPDATE users SET userid='" + userid + "' ,first_name ='" + firstname + "' ,last_name='" + lastname + "' ,email='" + email + "' ,password ='" + password + "' ,role ='" + role + "' , status ='" + status + "' WHERE userid = '" + userid + "'");
        JOptionPane.showMessageDialog(null, "Status Updated");
      } else {
        JOptionPane.showMessageDialog(null, "ERROR!");
      } 
    } catch (Exception e) {
      e.printStackTrace();
    } 
    }//GEN-LAST:event_changeroleActionPerformed

    private void txtuseridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuseridMouseClicked
      this.txtuserid.setText("");
    }//GEN-LAST:event_txtuseridMouseClicked

    private void txtfirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfirstnameMouseClicked
      this.txtfirstname.setText("");
    }//GEN-LAST:event_txtfirstnameMouseClicked

    private void txtlastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlastnameMouseClicked
      this.txtlastname.setText("");
    }//GEN-LAST:event_txtlastnameMouseClicked

    private void txtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseClicked
      this.txtemail.setText("");
    }//GEN-LAST:event_txtemailMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
      this.txtpassword.setText("");
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtroleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtroleMouseClicked
      this.txtrole.setText("");
    }//GEN-LAST:event_txtroleMouseClicked

    private void txtstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtstatusMouseClicked
      this.txtstatus.setText("");
    }//GEN-LAST:event_txtstatusMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
       login log = new login();
       this.dispose();
       log.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
       setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
       setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
      System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    adminhome portal = new adminhome();
    this.dispose();
    portal.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton changepassword;
    private javax.swing.JButton changerole;
    private javax.swing.JButton disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton manage;
    private javax.swing.JButton remove;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtrole;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtuserid;
    // End of variables declaration//GEN-END:variables
}
